# -*- coding: utf-8 -*-
"""Regressing_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctrxfNCc4KQjv-h68lmGvhl904RtbDG5
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# importing the dataset

data = pd.read_csv('ready_data.csv')
data.head()

data.describe()

data.info()

# feature scaling

y = data['Growth_Rate_Cent']

X_numeric = data[['Investment_Amount', 'Valuation',
                  'Number_of_Investors', 'Year_Founded']]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_numeric_scaled = pd.DataFrame(
    scaler.fit_transform(X_numeric),
    columns=X_numeric.columns
)

X_numeric_scaled.head()

# correlation map

# select only int and float columns
numeric_data = data.select_dtypes(include=['int64', 'float64'])

# correlation matrix
corrmat = numeric_data.corr()

# plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corrmat, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap (Numeric Columns Only)")
plt.show()

# laone-hot encoding the nominal variables.

X_categorical = pd.get_dummies(
    data[['Domain', 'Startup_Stage', 'Industry_Funder_Type']],
    drop_first=True
)

X_categorical.head()

# merge columns

X = pd.concat([X_numeric_scaled, X_categorical], axis=1)
y = data['Growth_Rate_Cent']

# train test splitting.

from sklearn.model_selection import train_test_split

# splitting the data
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# training the ml model

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error, mean_absolute_error

dt = DecisionTreeRegressor(
    criterion='squared_error',
    splitter='best',
    max_depth=5,
    min_samples_split=2
 )

dt.fit(x_train,y_train)

# model evaluation
y_pred = dt.predict(x_test)

MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)
RMSE = np.sqrt(MSE)
R2 = r2_score(y_test, y_pred)

print(f"MAE  : {MAE}")
print(f"MSE  : {MSE}")
print(f"RMSE : {RMSE}")
print(f"R²   : {R2}")

# plot tree
from sklearn.tree import plot_tree
plot_tree(dt)
plt.show()

# training random forest regressor

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=12,
    min_samples_leaf=3,
    random_state=42,
    n_jobs=-1
)

rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)

print("R²:", r2_score(y_test, y_pred))